apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminui
  labels:
    app: adminui
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: adminui
  template:
    metadata:
      labels:
        app: adminui
    spec:
      containers:
      - name: adminui
        image: lfy8/microservices-adminui:latest
        ports:
        - containerPort: 80 
        envFrom:
        - configMapRef:
            name: env      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: adminui
spec:
  selector:
    app: adminui
  ports:
    - name: adminui
      protocol: TCP
      port: 80
  type: LoadBalancer