apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogmanagement
  labels:
    app: catalogmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogmanagement
  template:
    metadata:
      labels:
        app: catalogmanagement
    spec:
      containers:
      - name: catalogmanagement
        image: lfy8/microservices-catalogmanagement:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: env
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: catalogmanagement
spec:
  selector:
    app: catalogmanagement
  ports:
    - name: catalogmanagement
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer