apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanagement
  labels:
    app: ordermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanagement
  template:
    metadata:
      labels:
        app: ordermanagement
    spec:
      containers:
      - name: ordermanagement
        image: lfy8/microservices-ordermanagement:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: env
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ordermanagement
spec:
  selector:
    app: ordermanagement
  ports:
    - name: ordermanagement
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer