apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: adminui
  labels:
    app: adminui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminui
  template:
    metadata:
      labels:
        app: adminui
    spec:
      securityContext:
        fsGroup: 1001 
      containers:
      - name: adminui
        image: lfy8/microservices-adminui:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: envconfig
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: adminui
spec:
  selector:
    app: adminui
  ports:
  - name: adminui
    protocol: TCP
    port: 44301
    targetPort: 80

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: default
  name: adminui
spec:
  to:
    kind: Service
    name: adminui
  port:
    targetPort: 80