apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ordermanagement
  labels:
    app: ordermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanagement
  template:
    metadata:
      labels:
        app: ordermanagement
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: ordermanagement
        image: lfy8/microservices-ordermanagement:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: envconfig
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ordermanagement
spec:
  selector:
    app: ordermanagement
  ports:
  - name: ordermanagement
    protocol: TCP
    port: 44399
    targetPort: 80

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: default
  name: ordermanagement
spec:
  to:
    kind: Service
    name: ordermanagement
  port:
    targetPort: 80